# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9447df66ddcd801eddd3ae3a011d5660945c493679470ee910896a7eb79a4d06e2f3e52b54fb40d8c2a6fc87c890cdf5e19f18ac8adaad5d0e0c9ec5ac258736

test:
  secret_key_base: 119ebdc475a80cc5eea7f0c84df2d18f19a9f1b7148fef68aaf985b455283790fd1c70bc7d5aef278401f348339b94c088c996007d9a08eca3cbd08f1a880225

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
